/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * This is a demo component to demonstrate the usage of StencilJS with Storybook.
     * @csspart greeting - Part for styling the greeting
     * @cssprop [--greeting-color=black] - Color of the greeting
     * @event my-event - This is a custom event
     */
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    /**
     * This is a demo component to demonstrate the usage of StencilJS with Storybook.
     * @csspart greeting - Part for styling the greeting
     * @cssprop [--greeting-color=black] - Color of the greeting
     * @event my-event - This is a custom event
     */
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    /**
     * This is a demo component to demonstrate the usage of StencilJS with Storybook.
     * @csspart greeting - Part for styling the greeting
     * @cssprop [--greeting-color=black] - Color of the greeting
     * @event my-event - This is a custom event
     */
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * This is a demo component to demonstrate the usage of StencilJS with Storybook.
             * @csspart greeting - Part for styling the greeting
             * @cssprop [--greeting-color=black] - Color of the greeting
             * @event my-event - This is a custom event
             */
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
